In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/hotel_bookings 2.csv")

In [4]:
print("shape of the data base is:",df.shape)

shape of the data base is: (119390, 32)

In [5]:
df_clean = df.copy()

print("Original shape:", df.shape)
print("Cleaning dataset shape:", df_clean.shape)

Original shape: (119390, 32)
Cleaning dataset shape: (119390, 32)

In [6]:
leakage_cols = [
    "reservation_status",
    "reservation_status_date",
    "assigned_room_type"
]

df_clean = df_clean.drop(columns=leakage_cols)

print("Shape after removing leakage columns:", df_clean.shape)

Shape after removing leakage columns: (119390, 29)

In [7]:
# check the null values 

df_clean.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
dtype: int64

In [8]:
df_clean["children"] = df_clean["children"].fillna(0)

In [9]:
#check for the null values in the childen column
df_clean["children"].isna().sum()

np.int64(0)

In [10]:
df_clean["country"] = df_clean["country"].fillna("Unknown")

In [11]:
df_clean["country"].isna().sum()

np.int64(0)

In [12]:
df_clean["agent"] = df_clean["agent"].fillna("Unknown")
df_clean["agent"] = df_clean["agent"].astype(str)

In [13]:
df_clean["company_missing"] = df_clean["company"].isna().astype(int)

In [14]:
df_clean = df_clean.drop(columns=["company"])

In [15]:
#preventing the negative adr 

df_clean["adr"] = df_clean["adr"].clip(lower=0)

In [16]:
print("Duplicate rows:", df_clean.duplicated().sum())

Duplicate rows: 33249

In [17]:
print("Final shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isna().sum()[df_clean.isna().sum() > 0])

print("\nDuplicate rows:", df_clean.duplicated().sum())

print("\nData types:")
print(df_clean.dtypes)

Final shape: (119390, 29)

Missing values:
Series([], dtype: int64)

Duplicate rows: 33249

Data types:
hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                              object
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
company_missing                     int64
dtype: object

In [18]:
df_clean[df_clean["adults"] > 10][
    ["adults", "children", "babies", "hotel", "market_segment", "customer_type", "adr", "is_canceled"]
]

,adults,children,babies,hotel,market_segment,customer_type,adr,is_canceled
1539,40,0.0,0,Resort Hotel,Direct,Group,0.0,1
1587,26,0.0,0,Resort Hotel,Offline TA/TO,Group,0.0,1
1643,50,0.0,0,Resort Hotel,Direct,Group,0.0,1
1752,26,0.0,0,Resort Hotel,Offline TA/TO,Group,0.0,1
1884,26,0.0,0,Resort Hotel,Offline TA/TO,Group,0.0,1
1917,27,0.0,0,Resort Hotel,Direct,Group,0.0,1
1962,27,0.0,0,Resort Hotel,Direct,Group,0.0,1
2003,26,0.0,0,Resort Hotel,Offline TA/TO,Group,0.0,1
2164,26,0.0,0,Resort Hotel,Offline TA/TO,Group,0.0,1
2173,55,0.0,0,Resort Hotel,Direct,Group,0.0,1
2228,20,0.0,0,Resort Hotel,Direct,Group,0.0,1
2418,20,0.0,0,Resort Hotel,Direct,Group,0.0,1

In [19]:
print("Adults > 10:", (df_clean["adults"] > 10).sum())
print(df_clean.loc[df_clean["adults"] > 10, "adults"].value_counts().sort_index())

Adults > 10: 12
adults
20    2
26    5
27    2
40    1
50    1
55    1
Name: count, dtype: int64

In [20]:
zero_guests = df_clean[
    (df_clean["adults"] == 0) &
    (df_clean["children"] == 0) &
    (df_clean["babies"] == 0)
]

print("Zero-guest bookings:", len(zero_guests))
zero_guests.head()

Zero-guest bookings: 180

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,reserved_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,company_missing
2224,Resort Hotel,0,1,2015,October,41,6,0,3,0,...,A,1,No Deposit,Unknown,0,Transient-Party,0.0,0,0,0
2409,Resort Hotel,0,0,2015,October,42,12,0,0,0,...,A,0,No Deposit,Unknown,0,Transient,0.0,0,0,0
3181,Resort Hotel,0,36,2015,November,47,20,1,2,0,...,A,0,No Deposit,38.0,0,Transient-Party,0.0,0,0,1
3684,Resort Hotel,0,165,2015,December,53,30,1,4,0,...,A,1,No Deposit,308.0,122,Transient-Party,0.0,0,0,1
3708,Resort Hotel,0,165,2015,December,53,30,2,4,0,...,A,1,No Deposit,308.0,122,Transient-Party,0.0,0,0,1

In [21]:
df_clean = df_clean[df_clean["adults"] <= 10].copy()

print("Shape after removing suspicious adults records:", df_clean.shape)

Shape after removing suspicious adults records: (119378, 29)

In [22]:
# Remove suspicious records with adults > 10
df_clean = df_clean[df_clean["adults"] <= 10].copy()

print("Final shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isna().sum()[df_clean.isna().sum() > 0])

print("\nDuplicate rows:", df_clean.duplicated().sum())

print("\nAdults > 10:", (df_clean["adults"] > 10).sum())

print("\nZero-guest bookings:")
print(
    (
        (df_clean["adults"] == 0) &
        (df_clean["children"] == 0) &
        (df_clean["babies"] == 0)
    ).sum()
)

Final shape: (119378, 29)

Missing values:
Series([], dtype: int64)

Duplicate rows: 33249

Adults > 10: 0

Zero-guest bookings:
180

In [23]:
df_clean.to_csv("../data/hotel_bookings_cleaned.csv", index=False)