In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/hotel_bookings_cleaned.csv")

print("Shape:", df.shape)
df.head()

Shape: (119378, 29)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,reserved_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,company_missing
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,C,3,No Deposit,Unknown,0,Transient,0.0,0,0,1
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,C,4,No Deposit,Unknown,0,Transient,0.0,0,0,1
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,A,0,No Deposit,Unknown,0,Transient,75.0,0,0,1
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,A,0,No Deposit,304.0,0,Transient,75.0,0,0,1
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,A,0,No Deposit,240.0,0,Transient,98.0,0,1,1

In [5]:
df["total_guests"] = (
    df["adults"] +
    df["children"] +
    df["babies"]
)

print(df["total_guests"].describe())

count    119378.000000
mean          1.965345
std           0.653271
min           0.000000
25%           2.000000
50%           2.000000
75%           2.000000
max          12.000000
Name: total_guests, dtype: float64

In [6]:
df[[
    "adults",
    "children",
    "babies",
    "total_guests"
]].head(10)

   adults  children  babies  total_guests
0       2       0.0       0           2.0
1       2       0.0       0           2.0
2       1       0.0       0           1.0
3       1       0.0       0           1.0
4       2       0.0       0           2.0
5       2       0.0       0           2.0
6       2       0.0       0           2.0
7       2       0.0       0           2.0
8       2       0.0       0           2.0
9       2       0.0       0           2.0

In [7]:
df["zero_guest_booking"] = (
    df["total_guests"] == 0
).astype(int)

print(df["zero_guest_booking"].value_counts())

zero_guest_booking
0    119198
1       180
Name: count, dtype: int64

In [8]:
df["total_stay_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

print(df["total_stay_nights"].describe())

count    119378.000000
mean          3.427700
std           2.557416
min           0.000000
25%           2.000000
50%           3.000000
75%           4.000000
max          69.000000
Name: total_stay_nights, dtype: float64

In [10]:
df["zero_stay_booking"] = (
    df["total_stay_nights"] == 0
).astype(int)

print(df["zero_stay_booking"].value_counts())

zero_stay_booking
0    118663
1       715
Name: count, dtype: int64

In [11]:
df["total_previous_bookings"] = (
    df["previous_cancellations"] +
    df["previous_bookings_not_canceled"]
)

print(df["total_previous_bookings"].describe())

count    119378.000000
mean          0.224237
std           1.828046
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max          78.000000
Name: total_previous_bookings, dtype: float64

In [12]:
df["previous_cancellation_rate"] = np.where(
    df["total_previous_bookings"] > 0,
    df["previous_cancellations"] / df["total_previous_bookings"],
    0
)

print(df["previous_cancellation_rate"].describe())

count    119378.000000
mean          0.050185
std           0.216523
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: previous_cancellation_rate, dtype: float64

In [13]:
df["has_previous_booking"] = (
    df["total_previous_bookings"] > 0
).astype(int)

print(df["has_previous_booking"].value_counts())

has_previous_booking
0    109921
1      9457
Name: count, dtype: int64

In [14]:
df["lead_time_group"] = pd.cut(
    df["lead_time"],
    bins=[-1, 7, 30, 90, 180, 365, np.inf],
    labels=[
        "0-7",
        "8-30",
        "31-90",
        "91-180",
        "181-365",
        "365+"
    ]
)

print(df["lead_time_group"].value_counts().sort_index())

lead_time_group
0-7        19746
8-30       18960
31-90      29553
91-180     26439
181-365    21532
365+        3148
Name: count, dtype: int64

In [15]:
df["has_special_request"] = (
    df["total_of_special_requests"] > 0
).astype(int)

print(df["has_special_request"].value_counts())

has_special_request
0    70306
1    49072
Name: count, dtype: int64

In [16]:
df["has_booking_changes"] = (
    df["booking_changes"] > 0
).astype(int)

print(df["has_booking_changes"].value_counts())

has_booking_changes
0    101303
1     18075
Name: count, dtype: int64

In [17]:
df["was_on_waiting_list"] = (
    df["days_in_waiting_list"] > 0
).astype(int)

print(df["was_on_waiting_list"].value_counts())

was_on_waiting_list
0    115680
1      3698
Name: count, dtype: int64

In [18]:
df["requires_parking"] = (
    df["required_car_parking_spaces"] > 0
).astype(int)

print(df["requires_parking"].value_counts())

requires_parking
0    111962
1      7416
Name: count, dtype: int64

In [19]:
df["has_children_or_babies"] = (
    (df["children"] > 0) |
    (df["babies"] > 0)
).astype(int)

print(df["has_children_or_babies"].value_counts())

has_children_or_babies
0    110046
1      9332
Name: count, dtype: int64

In [20]:
df["adr_per_guest"] = np.where(
    df["total_guests"] > 0,
    df["adr"] / df["total_guests"],
    0
)

print(df["adr_per_guest"].describe())

count    119378.000000
mean         54.911594
std          29.111398
min           0.000000
25%          37.400000
50%          49.500000
75%          66.000000
max        2700.000000
Name: adr_per_guest, dtype: float64

In [21]:
df["has_weekend_stay"] = (
    df["stays_in_weekend_nights"] > 0
).astype(int)

print(df["has_weekend_stay"].value_counts())

has_weekend_stay
1    67381
0    51997
Name: count, dtype: int64

In [22]:
month_mapping = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

df["arrival_month_num"] = df["arrival_date_month"].map(month_mapping)

print(df[[
    "arrival_date_month",
    "arrival_month_num"
]].head())

  arrival_date_month  arrival_month_num
0               July                  7
1               July                  7
2               July                  7
3               July                  7
4               July                  7

In [23]:
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"

df["arrival_season"] = df["arrival_month_num"].apply(get_season)

print(df["arrival_season"].value_counts())

arrival_season
Summer    37477
Spring    32674
Autumn    28450
Winter    20777
Name: count, dtype: int64

In [24]:
new_features = [
    "total_guests",
    "zero_guest_booking",
    "total_stay_nights",
    "zero_stay_booking",
    "total_previous_bookings",
    "previous_cancellation_rate",
    "has_previous_booking",
    "lead_time_group",
    "has_special_request",
    "has_booking_changes",
    "was_on_waiting_list",
    "requires_parking",
    "has_children_or_babies",
    "adr_per_guest",
    "has_weekend_stay",
    "arrival_month_num",
    "arrival_season"
]

print("New features created:")
for feature in new_features:
    print("-", feature)

New features created:
- total_guests
- zero_guest_booking
- total_stay_nights
- zero_stay_booking
- total_previous_bookings
- previous_cancellation_rate
- has_previous_booking
- lead_time_group
- has_special_request
- has_booking_changes
- was_on_waiting_list
- requires_parking
- has_children_or_babies
- adr_per_guest
- has_weekend_stay
- arrival_month_num
- arrival_season

In [25]:
print("Final shape:", df.shape)

print("\nMissing values:")
print(df.isna().sum()[df.isna().sum() > 0])

print("\nData types:")
print(df.dtypes)

Final shape: (119378, 46)

Missing values:
Series([], dtype: int64)

Data types:
hotel                               object
is_canceled                          int64
lead_time                            int64
arrival_date_year                    int64
arrival_date_month                  object
arrival_date_week_number             int64
arrival_date_day_of_month            int64
stays_in_weekend_nights              int64
stays_in_week_nights                 int64
adults                               int64
children                           float64
babies                               int64
meal                                object
country                             object
market_segment                      object
distribution_channel                object
is_repeated_guest                    int64
previous_cancellations               int64
previous_bookings_not_canceled       int64
reserved_room_type                  object
booking_changes                      int64
deposit_type                        object
agent                               object
days_in_waiting_list                 int64
customer_type                       object
adr                                float64
required_car_parking_spaces          int64
total_of_special_requests            int64
company_missing                      int64
total_guests                       float64
zero_guest_booking                   int64
total_stay_nights                    int64
zero_stay_booking                    int64
total_previous_bookings              int64
previous_cancellation_rate         float64
has_previous_booking                 int64
lead_time_group                   category
has_special_request                  int64
has_booking_changes                  int64
was_on_waiting_list                  int64
requires_parking                     int64
has_children_or_babies               int64
adr_per_guest                      float64
has_weekend_stay                     int64
arrival_month_num                    int64
arrival_season                      object
dtype: object

In [26]:
df[new_features].head(10)

,total_guests,zero_guest_booking,total_stay_nights,zero_stay_booking,total_previous_bookings,previous_cancellation_rate,has_previous_booking,lead_time_group,has_special_request,has_booking_changes,was_on_waiting_list,requires_parking,has_children_or_babies,adr_per_guest,has_weekend_stay,arrival_month_num,arrival_season
0,2.0,0,0,1,0,0.0,0,181-365,0,1,0,0,0,0.00,0,7,Summer
1,2.0,0,0,1,0,0.0,0,365+,0,1,0,0,0,0.00,0,7,Summer
2,1.0,0,1,0,0,0.0,0,0-7,0,0,0,0,0,75.00,0,7,Summer
3,1.0,0,1,0,0,0.0,0,8-30,0,0,0,0,0,75.00,0,7,Summer
4,2.0,0,2,0,0,0.0,0,8-30,1,0,0,0,0,49.00,0,7,Summer
5,2.0,0,2,0,0,0.0,0,8-30,1,0,0,0,0,49.00,0,7,Summer
6,2.0,0,2,0,0,0.0,0,0-7,0,0,0,0,0,53.50,0,7,Summer
7,2.0,0,2,0,0,0.0,0,8-30,1,0,0,0,0,51.50,0,7,Summer
8,2.0,0,3,0,0,0.0,0,31-90,1,0,0,0,0,41.00,0,7,Summer
9,2.0,0,3,0,0,0.0,0,31-90,0,0,0,0,0,52.75,0,7,Summer

In [27]:
df.to_csv(
    "../data/hotel_bookings_feature_engineered.csv",
    index=False
)

print("Feature-engineered dataset saved successfully.")

Feature-engineered dataset saved successfully.